name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  get_storage: ^2.1.1
  cloud_firestore: ^5.4.4
  image_picker: ^0.8.4+8
  file_picker: ^8.1.3
  firebase_storage: ^12.3.4
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/images/logo_app.png"
  min_sdk_android: 21

flutter:
  assets:
    - asset/images/logo.png
    - asset/images/logo_app.png
# Suggested code may be subject to a license. Learn more: ~LicenseLog:1755807307.
    - asset/images/polish_bg.jpg
  uses-material-design: true
